version: '3.7'

services:
  app:
    container_name: line_bot
    build: docker/app/
    ports:
      - '3001:8080'
    volumes:
      - ./app:/app
  nginx:
    container_name: line_bot_nginx
    build: docker/nginx/
    ports:
      - '3011:80'
